name: lb_tour
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_database: ^11.0.3
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  iconsax: ^0.0.8
  video_player: ^2.9.1
  fan_carousel_image_slider: ^1.0.1
  intl: ^0.20.1
  panorama_viewer: ^2.0.2
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  url_launcher: ^6.3.1
  latlong2: ^0.9.0
  permission_handler: ^11.3.1
  map_launcher: ^3.5.0

  flutter_inappwebview: ^6.0.0
  http: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
