name: lb_tour
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  iconsax: ^0.0.8
  video_player: ^2.9.1
  fan_carousel_image_slider: ^1.0.1
  intl: ^0.19.0
  panorama_viewer: ^1.0.6
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  flutter_inappwebview: ^6.0.0

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/